# Generated by Django 3.0.5 on 2020-04-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Camiseta pré-lavada e amaciada', 'Camiseta pré-lavada e amaciada'), ('Camiseta estonada', 'Camiseta estonada'), ('Camiseta tingida a seco', 'Camiseta tingida a seco'), ('Camiseta marmorizada', 'Camiseta marmorizada')], max_length=100)),
                ('cor', models.CharField(choices=[('Amarelo', 'Amarelo'), ('Azul', 'Azul'), ('Vermelho', 'Vermelho')], max_length=100)),
                ('tamanho', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=100)),
            ],
        ),
    ]
