# Generated by Django 3.0.5 on 2020-04-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
