# Generated by Django 3.0.5 on 2020-04-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_order_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estampada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='etiquetada',
            field=models.BooleanField(default=False),
        ),
    ]
