# Generated by Django 3.0.5 on 2020-04-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20200404_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='observaçoes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
