# Generated by Django 3.0.5 on 2020-04-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200405_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='observacoes',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
