# Generated by Django 3.0.5 on 2020-04-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20200405_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='observacoes',
            field=models.CharField(blank='', default='', max_length=100, null=True),
        ),
    ]
