# Generated by Django 3.0.5 on 2020-04-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20200405_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='observacoes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
