# Generated by Django 3.0.5 on 2020-04-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20200405_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pronta_entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100),
        ),
    ]
